export type Project = {
  id: string;
  client_id: string;
  name: string;
  description?: string | null;
  project_type?: string | null;
  status: string;
  domain?: string | null;
  domain_provider?: string | null;
  domain_renewal_date?: string | null;
  hosting_provider?: string | null;
  hosting_renewal_date?: string | null;
  repository_url?: string | null;
  production_url?: string | null;
  admin_url?: string | null;
  admin_username?: string | null;
  admin_password_note?: string | null;
  languages: string[];
  frameworks: string[];
  started_at?: string | null;
  delivered_at?: string | null;
  test_start_date?: string | null;
  test_end_date?: string | null;
  maintenance_end_date?: string | null;
  total_price: number;
  expenses: number;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  archived_at?: string | null;
  client_name?: string | null;
  paid_amount?: number;
  remaining_amount?: number;
  net_profit?: number;
};
